version: "3.7"

services:
  frontend:
    image: node
    container_name: frontend
    networks:
      - subtitles
    external_links:
      - cms
    ports:
      - 3000:3000
    volumes:
      - ./:/srv/app/
    restart: unless-stopped
    working_dir: /srv/app/
    entrypoint: "/bin/bash"
    command: "-c \"if [ ! -d \"node_modules\" ]; then npm i; fi; npm run dev\""

networks:
  subtitles:
    driver: bridge
    external: true
